### ISSUE TITLE
Use gitmoji 2.0.0 labels for the search

### ISSUE THREAD

**Issue by Tiv0w** [johannchopin/gitmoji-browser-extension#11]
Simply add the labels (gitmoji's description, like in #5 ) so we can search for example with "tests" because we might forget the `white_check_mark` shortcode. A bit like in the CLI.

**Comment by johannchopin** [comment]
Hey @Tiv0w thanks for giving a feedback 👍 

I don't really get it because we already have this feature in the extension. If you search `tests`
you will get:

- ✅ `:white_check_mark:`

<img width="354" alt="Screenshot 2020-07-21 at 19 45 38" src="https://user-images.githubusercontent.com/31794680/88088493-c9d00500-cb8a-11ea-95e3-169d5b75703c.png">

**Comment by Tiv0w** [comment]
Yeah my bad, i was not paying attention and i typed "update tests".

So the real issue I faced is that it is not using Gitmoji 2.0.0 labels, with **"add or update"**, but instead some have the old **"adding or updating"**

**Comment by johannchopin** [comment]
So the extension uses Gitmoji 2.0.0 as you can see in the [package.json](https://github.com/johannchopin/gitmoji-browser-extension/blob/master/package.json#L22) but you are right there was some old "adding or updating" that was fixed in this [PR#515](https://github.com/carloscuesta/gitmoji/pull/515). Will try to release asap Gitmoji 2.1.0 and use it in the extension 👍
