### ISSUE TITLE
[Feature request] Display gitmoji label next to its emoji name

### ISSUE THREAD

**Issue by KaKi87** [johannchopin/gitmoji-browser-extension#5]

**Comment by Lyokolux** [comment]
Hey @KaKi87 👋 , what do you mean by label ?

If you mean the description of the gitmojis, we don't want to add it because it will overload the display. The extension is meant to be fast for thoses who already knows which emoji they want to use. If you have a doubt, you can then click on the gitmoji logo to open the website.

The description is already a part of the search.

**Comment by KaKi87** [comment]
> If you mean the description of the gitmojis

Yes

> it will overload the display

Not with small font size and gray color.

> The extension is meant to be fast for thoses who already knows which emoji they want to use

Then, the emoji menu like `Win` + `.` on Windows works just fine.

> The description is already a part of the search.

I noticed that however, it's great !

**Comment by johannchopin** [comment]
Hey @KaKi87 👋 

Main goal of this extension is to easily have access to the gitmoji shortcode **and** the gitmoji emoji. Since not all tool support emoji shortcode (issue title for example) I always use the emoji directly instead of the shortcode. For this case the extension is a faster tool 👍 

Concerning the description I agreed with @Lyokolux. An extension stand to provide a fast and easy service. In the gitmoji-browser-extension case the goal is to find the right gitmoji shortcode or emoji faster without opening the website (so you have a little idea of what to search). If you don't know which gitmoji to use it's better to use the website 👍

**Comment by KaKi87** [comment]
Understood.
Then, why creating this tool as a Chrome extension instead of a system-wide tool ?

**Comment by johannchopin** [comment]
@KaKi87 We wanted to learn how to create an extension so we find it cool to work on a Gitmoji extension and there we are 😄

**Comment by KaKi87** [comment]
Okay. Well, if you ever consider creating a system-wide tool for Windows and Linux to copy/paste emojis and codes with descriptions, I'll be interested. Thanks
